###Check the given APIs:
GET https://lite-api.jup.ag/tokens/v2/search?query=DOGE

###Check the given APIs:
GET https://lite-api.jup.ag/tokens/v2/search?query=SOL

###Check the given APIs:
GET http://localhost:5001/home/getHomePage

###Check the given APIs:
GET http://localhost:5001/health